sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    max_update_rate: 5
    image_topic: /camera_side/depth/image_rect_raw
    queue_size: 2
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 4.0 # default value 4.0
    shadow_threshold: 0.8
    padding_scale: 2.0
    padding_offset: 0.05
    filtered_cloud_topic: filtered_cloud
    shape_padding: 0.05
    shape_scale: 1.0
    self_mask:
      min_sensor_dist: .8
      self_see_default_padding: .04
      self_see_default_scale: 1.0
      self_see_links:
        - name: edo_base_link
          padding: 0.1
        - name: edo_link_1
          padding: 0.1
        - name: edo_link_2
          padding: 0.1
        - name: edo_link_3
          padding: 0.1
        - name: edo_link_4
          padding: 0.1
        - name: edo_link_5
          padding: 0.1
        - name: edo_link_6
          padding: 0.1
        - name: edo_gripper_left_base_link
          padding: 0.1
        - name: edo_gripper_right_base_link
          padding: 0.1
        - name: edo_gripper_left_finger_link
          padding: 0.1
        - name: edo_gripper_right_finger_link
          padding: 0.1
        - name: edo_gripper_link
          padding: 0.1
        - name: edo_gripper_link_ee
          padding: 0.1
        - name: edo_link_ee
          padding: 0.1
